apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rabbitmq
    release: prometheus-operator
  name: rabbitmq
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: rabbitmq
      release: rabbitmq
  namespaceSelector:
    matchNames:
      - rabbitmq
  endpoints:
    - targetPort: 9090
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_service_label_hyperflow_namespace
          targetLabel: hyperflowNamespace
